# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      oauth_token:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'github oauth_token'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
      repos:
        description: 'target repos. `{owner}/{repos}`.'
        default: ''
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: step1
      run: python github-label-manager.py --oauth_token ${{ github.event.inputs.oauth_token }} --repos ${{ github.event.inputs.repos }}
